"""Computer Vision Portfolio - Modular classical image processing and vision toolkit."""

from __future__ import annotations

from .detection import (
    DetectionSummary,
    count_circular_objects,
    count_contours,
    detect_eyes,
    detect_faces,
    multi_scale_template_match,
    template_match,
)
from .features import (
    ContourProperties,
    MatchResult,
    contour_properties,
    draw_annotated_contours,
    fast_corners,
    find_external_contours,
    harris_corners,
    match_features_ratio_test,
    match_orb_features,
    orb_keypoints_and_descriptors,
    shi_tomasi_corners,
)
from .filtering import (
    bilateral_denoise,
    box_blur,
    canny_edges,
    compare_edge_detectors,
    custom_convolution,
    gaussian_denoise,
    gradient_vector_field,
    laplacian_edges,
    log_edges,
    median_filter,
    prewitt_edges,
    scharr_edges,
    sobel_edges,
    unsharp_mask,
)
from .preprocessing import (
    build_enhancement_summary,
    clahe_enhancement,
    color_histogram,
    compute_histogram_and_cdf,
    contrast_stretch,
    equalize_histogram,
    gamma_correction,
    gray_world_white_balance,
    log_transform,
    split_channels,
)
from .segmentation import (
    ComponentInfo,
    adaptive_threshold_gaussian,
    adaptive_threshold_mean,
    blackhat_transform,
    connected_components_summary,
    dilate_image,
    distance_transform_watershed,
    erode_image,
    filter_components_by_area,
    get_structuring_element,
    manual_threshold,
    morphological_gradient,
    morphology_cleanup,
    morphology_close,
    morphology_open,
    otsu_threshold,
    segmentation_pipeline,
    tophat_transform,
)
from .utils import (
    ImageStats,
    count_nonzero_ratio,
    ensure_uint8,
    generate_synthetic_image,
    image_stats,
    label_components,
    normalize_uint8,
    read_image,
    save_image,
    to_gray,
    to_hsv,
    to_lab,
    to_rgb,
)
from .visualization import plot_histogram_and_cdf, plot_image_grid

__version__ = "1.0.0"

__all__ = [
    # Subpackages
    "preprocessing",
    "filtering",
    "segmentation",
    "features",
    "detection",
    "visualization",
    "utils",
    # Utils
    "ImageStats",
    "image_stats",
    "read_image",
    "save_image",
    "generate_synthetic_image",
    "to_gray",
    "to_rgb",
    "to_hsv",
    "to_lab",
    "normalize_uint8",
    "ensure_uint8",
    "count_nonzero_ratio",
    "label_components",
    # Preprocessing
    "contrast_stretch",
    "gamma_correction",
    "log_transform",
    "equalize_histogram",
    "clahe_enhancement",
    "compute_histogram_and_cdf",
    "build_enhancement_summary",
    "split_channels",
    "gray_world_white_balance",
    "color_histogram",
    # Filtering
    "custom_convolution",
    "box_blur",
    "gaussian_denoise",
    "median_filter",
    "bilateral_denoise",
    "unsharp_mask",
    "gradient_vector_field",
    "sobel_edges",
    "prewitt_edges",
    "scharr_edges",
    "laplacian_edges",
    "log_edges",
    "canny_edges",
    "compare_edge_detectors",
    # Segmentation
    "manual_threshold",
    "otsu_threshold",
    "adaptive_threshold_mean",
    "adaptive_threshold_gaussian",
    "get_structuring_element",
    "erode_image",
    "dilate_image",
    "morphology_open",
    "morphology_close",
    "morphological_gradient",
    "tophat_transform",
    "blackhat_transform",
    "morphology_cleanup",
    "ComponentInfo",
    "connected_components_summary",
    "filter_components_by_area",
    "distance_transform_watershed",
    "segmentation_pipeline",
    # Features
    "harris_corners",
    "shi_tomasi_corners",
    "fast_corners",
    "MatchResult",
    "orb_keypoints_and_descriptors",
    "match_orb_features",
    "match_features_ratio_test",
    "ContourProperties",
    "find_external_contours",
    "contour_properties",
    "draw_annotated_contours",
    # Detection
    "DetectionSummary",
    "detect_faces",
    "detect_eyes",
    "template_match",
    "multi_scale_template_match",
    "count_contours",
    "count_circular_objects",
    # Visualization
    "plot_image_grid",
    "plot_histogram_and_cdf",
]
